baseEndpointUrl: 'https://dev.api.mincepiechallenge.com'
userPoolName: 'dev-mince-pie-challenge-pool'
userPoolId:
  Ref: PieUserPool
userPoolClientName: 'dev-mince-pie-challenge-client'
userPoolClientId:
  Ref: PieUserPoolClient
