version: '3'

services:
  serverless:
    build: .
    env_file: .env
    volumes:
      - .:/opt/app
      - app-modules:/opt/app/node_modules
  serverless-offline:
    build: .
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
      - app-modules:/opt/app/node_modules
    links:
      - dynamodb
  dynamodb:
    image: ccabreraruiz/dynamodb-local
    ports:
      - 8000:8000
  aws-cli:
    image: mesosphere/aws-cli
    env_file: .env

volumes:
  app-modules:
