version: '3'

services:
  serverless:
    build: .
    env_file: .env
    volumes:
      - .:/opt/app
      - app-modules:/opt/app/node_modules
  aws-cli:
    image: mesosphere/aws-cli
    env_file: .env

volumes:
  app-modules:
